const mentors = [
  {
    id: "mentor-1",
    name: "Alexandra Chen",
    university: "Stanford University",
    major: "Computer Science",
    bio: "CS major specializing in artificial intelligence and machine learning. I've interned at Google and worked on research projects in NLP.",
    avatar:
      "https://images.unsplash.com/photo-1649972904349-6e44c42644a7?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 47,
    expertise_areas: [
      "Machine Learning",
      "Algorithm Design",
      "College Apps",
      "Internships",
    ],
    hourly_rate: 45,
    availability: "Evenings & Weekends",
    type: "graduate",
  },
  {
    id: "mentor-2",
    name: "Marcus Johnson",
    university: "Harvard University",
    major: "Biology (Pre-Med)",
    bio: "Pre-med student with research experience in immunology. I can help with MCAT prep, biology coursework, and medical school applications.",
    avatar:
      "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.7,
    rating_count: 32,
    expertise_areas: ["MCAT Prep", "Biology", "Chemistry", "Research"],
    hourly_rate: 50,
    availability: "Weekday afternoons",
    type: "graduate",
  },
  {
    id: "mentor-3",
    name: "Dr. Sophia Rodriguez",
    university: "MIT",
    major: "Physics",
    bio: "Physics professor with 10+ years of experience. I've published numerous papers in quantum mechanics and can help with advanced physics concepts.",
    avatar:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 28,
    expertise_areas: ["Physics", "Mathematics", "Research", "Olympiads"],
    hourly_rate: 60,
    availability: "Flexible",
    type: "professor",
  },
  {
    id: "mentor-4",
    name: "David Park",
    university: "Yale University",
    major: "English Literature",
    bio: "English major passionate about creative writing and literary analysis. I can help with essay writing, university applications, and humanities coursework.",
    avatar:
      "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=150&h=150&q=80",
    avg_rating: 4.6,
    rating_count: 19,
    expertise_areas: [
      "Essay Writing",
      "Literature",
      "College Apps",
      "Creative Writing",
    ],
    hourly_rate: 35,
    availability: "Weekends",
    type: "graduate",
  },
  {
    id: "mentor-5",
    name: "Jasmine Williams",
    university: "Princeton University",
    major: "Economics",
    bio: "Economics major with experience in data analysis and market research. I've interned at Morgan Stanley and can help with economics courses and business studies.",
    avatar:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 38,
    expertise_areas: ["Economics", "Finance", "Data Analysis", "Internships"],
    hourly_rate: 45,
    availability: "Weekday evenings",
    type: "graduate",
  },
  {
    id: "mentor-6",
    name: "Dr. Robert Chen",
    university: "Stanford University",
    major: "Computer Science",
    bio: "Professor of Computer Science with 15 years of experience. Specializing in artificial intelligence and machine learning algorithms.",
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 62,
    expertise_areas: ["AI", "Machine Learning", "Programming", "Research"],
    hourly_rate: 75,
    availability: "By appointment",
    type: "professor",
  },
  {
    id: "mentor-7",
    name: "Dr. Maria Garcia",
    university: "Harvard University",
    major: "Chemistry",
    bio: "Chemistry professor with focus on organic synthesis. I've mentored dozens of students through their thesis projects and research.",
    avatar:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 43,
    expertise_areas: [
      "Chemistry",
      "Research Methods",
      "Lab Techniques",
      "STEM Education",
    ],
    hourly_rate: 65,
    availability: "Weekday mornings",
    type: "professor",
  },
  {
    id: "professor-1",
    name: "Dr. James Wilson",
    university: "Princeton University",
    major: "Mathematics",
    bio: "Mathematics professor specializing in number theory and cryptography. Over 15 years of teaching experience with numerous published papers in leading journals.",
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 57,
    expertise_areas: [
      "Number Theory",
      "Cryptography",
      "Advanced Calculus",
      "Mathematical Logic",
    ],
    hourly_rate: 70,
    availability: "Weekday afternoons",
    type: "professor",
  },
  {
    id: "professor-2",
    name: "Dr. Emily Zhang",
    university: "Columbia University",
    major: "Neuroscience",
    bio: "Neuroscience professor researching brain plasticity and cognitive development. Previously led research teams at Johns Hopkins and has mentored over 30 PhD students.",
    avatar:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 41,
    expertise_areas: [
      "Neuroscience",
      "Brain Development",
      "Research Methods",
      "Scientific Writing",
    ],
    hourly_rate: 75,
    availability: "Flexible schedule",
    type: "professor",
  },
  {
    id: "professor-3",
    name: "Dr. Thomas Reynolds",
    university: "California Institute of Technology",
    major: "Physics",
    bio: "Theoretical physicist with research focus on quantum mechanics and string theory. Part of the team that contributed to the Higgs boson discovery.",
    avatar:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 38,
    expertise_areas: [
      "Quantum Physics",
      "String Theory",
      "Particle Physics",
      "Mathematics",
    ],
    hourly_rate: 80,
    availability: "Evenings and weekends",
    type: "professor",
  },
  {
    id: "professor-4",
    name: "Dr. Sarah Johnson",
    university: "University of Chicago",
    major: "Economics",
    bio: "Professor of Economics specializing in macroeconomic theory and international trade. Former advisor to the Federal Reserve with extensive policy experience.",
    avatar:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.7,
    rating_count: 46,
    expertise_areas: [
      "Macroeconomics",
      "International Trade",
      "Economic Policy",
      "Research",
    ],
    hourly_rate: 65,
    availability: "Weekday mornings",
    type: "professor",
  },
  {
    id: "professor-5",
    name: "Dr. Michael Chen",
    university: "Cornell University",
    major: "Computer Engineering",
    bio: "Professor of Computer Engineering with expertise_areas in VLSI design and embedded systems. Holds multiple patents and has founded two successful tech startups.",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 52,
    expertise_areas: [
      "VLSI Design",
      "Embedded Systems",
      "Circuit Design",
      "Tech Entrepreneurship",
    ],
    hourly_rate: 75,
    availability: "Weekends only",
    type: "professor",
  },
  {
    id: "professor-6",
    name: "Dr. Lisa Rodriguez",
    university: "University of Pennsylvania",
    major: "Psychology",
    bio: "Clinical psychology professor with research focusing on cognitive behavioral therapies. Maintains a private practice and has authored three books on psychology.",
    avatar:
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 63,
    expertise_areas: [
      "Clinical Psychology",
      "Cognitive Therapy",
      "Research Methods",
      "Mental Health",
    ],
    hourly_rate: 70,
    availability: "Flexible schedule",
    type: "professor",
  },
  {
    id: "professor-7",
    name: "Dr. Richard Patel",
    university: "Duke University",
    major: "Biology",
    bio: "Professor of Molecular Biology specializing in genomics and gene therapy. Has led breakthrough research in CRISPR applications for treating genetic disorders.",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 44,
    expertise_areas: [
      "Molecular Biology",
      "Genomics",
      "CRISPR",
      "Medical Research",
    ],
    hourly_rate: 80,
    availability: "By appointment",
    type: "professor",
  },
  {
    id: "professor-8",
    name: "Dr. Margaret Williams",
    university: "Brown University",
    major: "English Literature",
    bio: "Professor of Renaissance Literature with focus on Shakespeare and his contemporaries. Published numerous scholarly articles and is a frequent consultant for theater productions.",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.7,
    rating_count: 39,
    expertise_areas: [
      "Shakespeare",
      "Renaissance Literature",
      "Literary Criticism",
      "Academic Writing",
    ],
    hourly_rate: 60,
    availability: "Afternoons only",
    type: "professor",
  },
  {
    id: "professor-9",
    name: "Dr. Alan Foster",
    university: "Northwestern University",
    major: "Chemical Engineering",
    bio: "Chemical Engineering professor researching sustainable materials and green chemistry. Previously led R&D at a major chemical company and holds multiple patents.",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.8,
    rating_count: 47,
    expertise_areas: [
      "Green Chemistry",
      "Sustainable Materials",
      "Process Engineering",
      "Patents",
    ],
    hourly_rate: 75,
    availability: "Weekday evenings",
    type: "professor",
  },
  {
    id: "professor-10",
    name: "Dr. Julia Martinez",
    university: "Johns Hopkins University",
    major: "Public Health",
    bio: "Professor of Epidemiology with extensive experience in global health initiatives. Has worked with WHO and led pandemic preparedness programs across multiple countries.",
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=150&h=150",
    avg_rating: 4.9,
    rating_count: 51,
    expertise_areas: [
      "Epidemiology",
      "Global Health",
      "Public Policy",
      "Biostatistics",
    ],
    hourly_rate: 70,
    availability: "Flexible schedule",
    type: "professor",
  },
];

export default mentors;
